export const countries = [
  { code: "US", en: "United States", zh: "美国" },
  { code: "CN", en: "China", zh: "中国" },
  { code: "JP", en: "Japan", zh: "日本" },
  { code: "DE", en: "Germany", zh: "德国" },
  { code: "FR", en: "France", zh: "法国" },
  { code: "GB", en: "United Kingdom", zh: "英国" },
  { code: "CA", en: "Canada", zh: "加拿大" },
  { code: "KR", en: "South Korea", zh: "韩国" },
  { code: "IN", en: "India", zh: "印度" },
  { code: "IT", en: "Italy", zh: "意大利" },
  { code: "RU", en: "Russia", zh: "俄罗斯" },
  { code: "BR", en: "Brazil", zh: "巴西" },
  { code: "AU", en: "Australia", zh: "澳大利亚" },
  { code: "ES", en: "Spain", zh: "西班牙" },
  { code: "MX", en: "Mexico", zh: "墨西哥" },
  { code: "ID", en: "Indonesia", zh: "印度尼西亚" },
  { code: "TR", en: "Turkey", zh: "土耳其" },
  { code: "SA", en: "Saudi Arabia", zh: "沙特阿拉伯" },
  { code: "AR", en: "Argentina", zh: "阿根廷" },
  { code: "ZA", en: "South Africa", zh: "南非" },
  { code: "SE", en: "Sweden", zh: "瑞典" },
  { code: "CH", en: "Switzerland", zh: "瑞士" },
  { code: "NL", en: "Netherlands", zh: "荷兰" },
  { code: "BE", en: "Belgium", zh: "比利时" },
  { code: "PL", en: "Poland", zh: "波兰" },
  { code: "TH", en: "Thailand", zh: "泰国" },
  { code: "EG", en: "Egypt", zh: "埃及" },
  { code: "NG", en: "Nigeria", zh: "尼日利亚" },
  { code: "PK", en: "Pakistan", zh: "巴基斯坦" },
  { code: "BD", en: "Bangladesh", zh: "孟加拉国" },
  { code: "VN", en: "Vietnam", zh: "越南" },
  { code: "PH", en: "Philippines", zh: "菲律宾" },
  { code: "MY", en: "Malaysia", zh: "马来西亚" },
  { code: "SG", en: "Singapore", zh: "新加坡" },
  { code: "HK", en: "Hong Kong", zh: "中国香港" },
  { code: "TW", en: "Taiwan", zh: "中国台湾" },
  { code: "UA", en: "Ukraine", zh: "乌克兰" },
  { code: "AT", en: "Austria", zh: "奥地利" },
  { code: "NO", en: "Norway", zh: "挪威" },
  { code: "DK", en: "Denmark", zh: "丹麦" },
  { code: "FI", en: "Finland", zh: "芬兰" },
  { code: "IE", en: "Ireland", zh: "爱尔兰" },
  { code: "IL", en: "Israel", zh: "以色列" },
  { code: "GR", en: "Greece", zh: "希腊" },
  { code: "PT", en: "Portugal", zh: "葡萄牙" },
  { code: "HU", en: "Hungary", zh: "匈牙利" },
  { code: "CZ", en: "Czech Republic", zh: "捷克" },
  { code: "NZ", en: "New Zealand", zh: "新西兰" },
]; 